package com.example.mymemo.db

/**
 * 内置预制词表(约 150 个常用四级词汇,单词 + 简短中文释义)。
 *
 * 首次创建数据库时由 [AppDatabaseHelper] 批量播种,全账号共享。
 */
object PresetWords {

    /** 单词对(英文, 中文释义)。 */
    val ENTRIES: List<Pair<String, String>> = listOf(
        "abandon" to "v. 放弃,抛弃",
        "ability" to "n. 能力,才能",
        "absolute" to "adj. 绝对的,完全的",
        "accept" to "v. 接受,承认",
        "access" to "n. 通道;访问权",
        "accident" to "n. 事故,意外",
        "account" to "n. 账户;账目",
        "accurate" to "adj. 准确的,精确的",
        "achieve" to "v. 实现,达到",
        "active" to "adj. 积极的,活跃的",
        "actual" to "adj. 实际的,真实的",
        "adapt" to "v. 适应,改编",
        "admire" to "v. 钦佩,赞赏",
        "admit" to "v. 承认;准许进入",
        "advance" to "v. 前进;促进",
        "advantage" to "n. 优势,好处",
        "adventure" to "n. 冒险,奇遇",
        "advertise" to "v. 做广告,宣传",
        "advise" to "v. 建议,劝告",
        "affect" to "v. 影响,感动",
        "afford" to "v. 负担得起,提供",
        "agree" to "v. 同意,赞成",
        "aim" to "n. 目标;v. 瞄准",
        "allow" to "v. 允许,准许",
        "amount" to "n. 数量,总额",
        "ancient" to "adj. 古代的,古老的",
        "announce" to "v. 宣布,声明",
        "anxious" to "adj. 焦虑的,渴望的",
        "apart" to "adv. 分开地,相距",
        "apologize" to "v. 道歉,谢罪",
        "appeal" to "v. 呼吁;有吸引力",
        "appear" to "v. 出现,显得",
        "apply" to "v. 申请,应用",
        "appreciate" to "v. 感激,欣赏",
        "approach" to "v. 接近;n. 方法",
        "appropriate" to "adj. 适当的,合适的",
        "argue" to "v. 争论,辩论",
        "arrange" to "v. 安排,整理",
        "arrive" to "v. 到达,抵达",
        "attend" to "v. 出席,参加",
        "attitude" to "n. 态度,看法",
        "attract" to "v. 吸引,引起",
        "average" to "adj. 平均的;n. 平均数",
        "avoid" to "v. 避免,躲开",
        "aware" to "adj. 意识到的,知道的",
        "balance" to "n. 平衡;余额",
        "benefit" to "n. 利益;v. 受益",
        "borrow" to "v. 借入,借用",
        "brief" to "adj. 简短的,短暂的",
        "broad" to "adj. 宽阔的,广泛的",
        "budget" to "n. 预算,经费",
        "calculate" to "v. 计算,估计",
        "campaign" to "n. 运动,战役",
        "cancel" to "v. 取消,撤销",
        "capable" to "adj. 有能力的,能干的",
        "capital" to "n. 首都;资本",
        "career" to "n. 职业,生涯",
        "carry" to "v. 携带,运送",
        "cause" to "n. 原因;v. 引起",
        "challenge" to "n. 挑战;v. 质疑",
        "character" to "n. 性格,角色",
        "charge" to "v. 收费;充电",
        "choice" to "n. 选择,抉择",
        "claim" to "v. 声称,索取",
        "climate" to "n. 气候,风气",
        "combine" to "v. 结合,联合",
        "comfort" to "n. 舒适;安慰",
        "comment" to "n. 评论,意见",
        "commit" to "v. 犯(错);承诺",
        "communicate" to "v. 交流,沟通",
        "compare" to "v. 比较,对照",
        "compete" to "v. 竞争,比赛",
        "complain" to "v. 抱怨,投诉",
        "complete" to "v. 完成;adj. 完整的",
        "concern" to "n. 关心,忧虑",
        "condition" to "n. 条件,状况",
        "conduct" to "v. 进行;n. 行为",
        "confirm" to "v. 确认,证实",
        "confuse" to "v. 使困惑,混淆",
        "connect" to "v. 连接,联系",
        "consider" to "v. 考虑,认为",
        "consist" to "v. 由……组成",
        "contact" to "v. 联系;n. 接触",
        "contain" to "v. 包含,容纳",
        "continue" to "v. 继续,持续",
        "contribute" to "v. 贡献,捐助",
        "control" to "v. 控制;n. 控制权",
        "convenient" to "adj. 方便的,便利的",
        "convince" to "v. 使确信,说服",
        "courage" to "n. 勇气,胆量",
        "create" to "v. 创造,创建",
        "culture" to "n. 文化,教养",
        "current" to "adj. 当前的;n. 水流",
        "damage" to "v. 损害;n. 损失",
        "debate" to "n. 辩论;v. 讨论",
        "decide" to "v. 决定,决心",
        "decline" to "v. 下降;婉拒",
        "decrease" to "v. 减少;n. 下降",
        "defend" to "v. 保卫,辩护",
        "delay" to "v. 延误;n. 耽搁",
        "deliver" to "v. 递送,发表",
        "demand" to "n. 需求;v. 要求",
        "deny" to "v. 否认,拒绝",
        "depend" to "v. 依靠,取决于",
        "describe" to "v. 描述,形容",
        "deserve" to "v. 应得,值得",
        "design" to "v. 设计;n. 图案",
        "desire" to "n. 愿望;v. 渴望",
        "destroy" to "v. 破坏,摧毁",
        "detail" to "n. 细节,详情",
        "develop" to "v. 发展,开发",
        "difference" to "n. 差异,不同",
        "difficult" to "adj. 困难的,艰难的",
        "direct" to "adj. 直接的;v. 指导",
        "discover" to "v. 发现,发觉",
        "discuss" to "v. 讨论,商议",
        "distance" to "n. 距离,远方",
        "disturb" to "v. 打扰,扰乱",
        "divide" to "v. 分开,划分",
        "doubt" to "n. 怀疑;v. 怀疑",
        "economy" to "n. 经济,节约",
        "educate" to "v. 教育,培养",
        "effect" to "n. 影响,效果",
        "effort" to "n. 努力,尝试",
        "elect" to "v. 选举,推选",
        "employ" to "v. 雇用,使用",
        "encourage" to "v. 鼓励,支持",
        "energy" to "n. 能量,精力",
        "engage" to "v. 从事,参与",
        "enjoy" to "v. 享受,喜爱",
        "ensure" to "v. 确保,保证",
        "environment" to "n. 环境,外界",
        "equal" to "adj. 相等的;v. 等于",
        "escape" to "v. 逃跑,逃避",
        "establish" to "v. 建立,确立",
        "estimate" to "v. 估计;n. 评估",
        "evidence" to "n. 证据,迹象",
        "examine" to "v. 检查,审查",
        "exchange" to "v. 交换;n. 交流",
        "exist" to "v. 存在,生存",
        "expand" to "v. 扩大,扩展",
        "expect" to "v. 期望,预料",
        "experience" to "n. 经验,经历",
        "explain" to "v. 解释,说明",
        "express" to "v. 表达;adj. 快速的",
        "extend" to "v. 延伸,扩展",
        "familiar" to "adj. 熟悉的,常见的",
        "feature" to "n. 特征,特色",
        "fetch" to "v. 取来,接来",
        "figure" to "n. 数字,人物",
        "focus" to "v. 集中;n. 焦点",
        "follow" to "v. 跟随,遵循"
    )
}
